name: Build LaTeX eBook

on:
  push:
    branches: [ "devel" ]
  pull_request:
    branches: [ "devel" ]

jobs:
  build-latex-ebook:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install build dependencies
      run:  sudo apt-get install -y --no-install-recommends fonts-cns11643-kai fonts-hanazono fonts-noto-cjk fonts-noto-cjk-extra texlive-full

    - name: Install extra fonts
      run:  mkdir ~/.fonts && cp fonts/*.otf ~/.fonts

    - name: Build
      run:  cd latex && make

    - name: Upload LaTeX ebook
      uses:  actions/upload-artifact@v3
      with:
        name: sichuan-cookbook-pdf
        path: latex/sichuan-cookbook.pdf
        if-no-files-found: error
        retention-days: 90
