name: Build the LaTeX book.

on:
  push:
    branches: [ "github-action" ]
  pull_request:
    branches: [ "github-action" ]

jobs:
  build-latex-ebook:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Install build dependencies
      run:  sudo apt-get install -y --no-install-recommends fonts-cns11643-kai fonts-hanazono fonts-noto texlive-full

    - name: Build
      run:  cd latex && make

    - name: Upload LaTeX ebook
      use:  actions/upload-artifact@v3
      with:
        name: sichuan-cookbook-pdf
        path: latex/sichuan-cookbook.pdf
