name: Build LaTeX eBook

on:
  push:
    branches: [ "v1.0" ]
  pull_request:
    branches: [ "v1.0" ]

jobs:
  build-latex-ebook:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Download extra fonts
      run:  mkdir -p ~/.fonts && curl https://glyphwiki.org/font/gw2696945.ttf -o ~/.fonts/sim-ch_n5100_gw2696945.ttf

    - name: Update the package index
      run:  sudo apt-get update

    - name: Install build dependencies
      run:  sudo apt-get install -y --no-install-recommends fonts-cns11643-kai fonts-hanazono fonts-noto-cjk fonts-noto-cjk-extra texlive-full

    - name: Build
      run:  cd latex && make all

    - name: Upload LaTeX ebook
      uses:  actions/upload-artifact@v4
      with:
        name: sichuan-cookbook-pdf
        path: |
          latex/book-cover.pdf
          latex/sichuan-cookbook.pdf
        if-no-files-found: error
        retention-days: 90
